AWSTemplateFormatVersion: "2010-09-09"
Description: AppSync CloudFormation template

Resources:
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: "${stackName}-${graphQlApiName}"
      AuthenticationType: "AMAZON_COGNITO_USER_POOLS"
      UserPoolConfig:
        UserPoolId: "${userPoolId}"
        AwsRegion: "${AWS::Region}"
        DefaultAction: "ALLOW"

  GraphQLSchema:
      Type: AWS::AppSync::GraphQLSchema
      Properties:
        ApiId: !GetAtt [GraphQLApi, ApiId]
        Definition: "${file(./stacks/${stackFolder}/schema.graphql)}"


Outputs:
  GraphQLApiId:
    Description: GraphQLApi Id
    Value: !GetAtt [ GraphQLApi, ApiId ]

  GraphQLApiArn:
    Description: GraphQLApi Arn
    Value: !GetAtt [ GraphQLApi, Arn ]

  GraphQLApiUrl:
    Description: GraphQLApi URL
    Value: !GetAtt [ GraphQLApi, GraphQLUrl ]