AWSTemplateFormatVersion: '2010-09-09'
Description: The AWS CloudFormation template for this Serverless application

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/lambda/${stackName}"
      RetentionInDays: 7

  IamRoleLambdaExecution:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      RoleName: "${stackName}-LambdaRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: "${stackName}-LambdaPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${stackName}*:*"
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${stackName}*:*:*"
      
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: "${projectDeploymentBucketName}"
        S3Key: "${lambdaCodeBucketKey}"
      FunctionName: "${functionName}"
      Handler: handler.${handlerName}
      MemorySize: ${memorySize}
      Role: !GetAtt [IamRoleLambdaExecution, Arn]
      Runtime: ${runtime}
      Timeout: ${timeout}
      Environment:
        Variables:
          STAGE: dev
    DependsOn:
      - LogGroup
      - IamRoleLambdaExecution

Outputs:  
  LambdaFunctionArn:
    Value: !GetAtt [LambdaFunction, Arn]