AWSTemplateFormatVersion: "2010-09-09"
Description: AppSync CloudFormation template for DynamoDB DataSource

Resources:

  Datasource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: ${graphQLApiId}
      Name: "${tableName}Ds"
      Description: "AppSync DataSource for ${tableName}"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt [ DatasourceRole, Arn ]
      DynamoDBConfig:
        AwsRegion: "${AwsRegion}"
        TableName: "${tableName}"
        UseCallerCredentials: false

  DatasourceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "${stackName}-${tableName}-DsRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - appsync.amazonaws.com
            Action:
                - sts:AssumeRole
      Policies:
        - PolicyName: "${stackName}-${tableName}-DsRolePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}
                  - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}/*

  ## Pipeline Function and Resolver to GetItem

  GraphQlFunctionConfigurationGetItem:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId: ${graphQLApiId}
      Name: GraphQlFunctionConfigurationGetItem
      DataSourceName: !GetAtt [Datasource, Name]
      RequestMappingTemplate: "${file(./stacks/${stackName}/resolvers/GetItem.request.vtl)}"
      ResponseMappingTemplate: "${file(./stacks/${stackName}/resolvers/GetItem.response.vtl)}"
      FunctionVersion: '2018-05-29'

  GraphQlResolverQueryGetItem:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: ${graphQLApiId}
      TypeName: Query
      FieldName: ${getItemFieldName}
      RequestMappingTemplate: "${file(./stacks/${stackName}/resolvers/request.before.vtl)}"
      ResponseMappingTemplate: "${file(./stacks/${stackName}/resolvers/response.after.vtl)}"
      Kind: PIPELINE
      PipelineConfig:
        Functions:
          - !GetAtt [GraphQlFunctionConfigurationGetItem, FunctionId]

  ## Pipeline Function and Resolver to CreateItem

  GraphQlFunctionConfigurationCreateItem:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId: ${graphQLApiId}
      Name: GraphQlFunctionConfigurationCreateItem
      DataSourceName: !GetAtt [Datasource, Name]
      RequestMappingTemplate: "${file(./stacks/${stackName}/resolvers/CreateItem.request.vtl)}"
      ResponseMappingTemplate: "${file(./stacks/${stackName}/resolvers/CreateItem.response.vtl)}"
      FunctionVersion: '2018-05-29'

  GraphQlResolverQueryCreateItem:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: ${graphQLApiId}
      TypeName: Mutation
      FieldName: ${createItemFieldName}
      RequestMappingTemplate: "${file(./stacks/${stackName}/resolvers/request.before.vtl)}"
      ResponseMappingTemplate: "${file(./stacks/${stackName}/resolvers/response.after.vtl)}"
      Kind: PIPELINE
      PipelineConfig:
        Functions:
          - !GetAtt [GraphQlFunctionConfigurationCreateItem, FunctionId]
